http://localhost:3001

###
GET http://localhost:3001/api/users/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU3OTM3ZWZmNDI5NzBlZmIyMDJhZTEiLCJmaXJzdG5hbWUiOiJTaGl2aSIsImxhc3RuYW1lIjoiaGV5IiwiaGFuZGxlIjoic2hpdiIsImVtYWlsIjoic2hpdkBnbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yMS5qcGciLCJpZCI6NiwiaWF0IjoxNjUwMzExMDQyfQ.GcuNIXHFODaZoP2hivad-__DggiE2v9O5tLQTyurAII

###
GET http://localhost:3001/api/users/handle/shivi
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU3OTM3ZWZmNDI5NzBlZmIyMDJhZTEiLCJmaXJzdG5hbWUiOiJTaGl2aSIsImxhc3RuYW1lIjoiaGV5IiwiaGFuZGxlIjoic2hpdiIsImVtYWlsIjoic2hpdkBnbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yMS5qcGciLCJpZCI6NiwiaWF0IjoxNjUwMzExMDQyfQ.GcuNIXHFODaZoP2hivad-__DggiE2v9O5tLQTyurAII

###
GET http://localhost:3001/api/users/62665f5510330fac1ebfce25

###
DELETE  http://localhost:3001/api/users/62665f5510330fac1ebfce25
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU3OTM3ZWZmNDI5NzBlZmIyMDJhZTEiLCJmaXJzdG5hbWUiOiJTaGl2aSIsImxhc3RuYW1lIjoiaGV5IiwiaGFuZGxlIjoic2hpdiIsImVtYWlsIjoic2hpdkBnbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yMS5qcGciLCJpZCI6NiwiaWF0IjoxNjUwMzExMDQyfQ.GcuNIXHFODaZoP2hivad-__DggiE2v9O5tLQTyurAII



###
POST http://localhost:3001/api/users
Content-Type: application/json
{
    "firstname": "Shivi",
    "lastname": "hey",
    "handle": "shiv",
    "password": "coffee",
    "email": "shivi@gmail.com",
    "pic": "https://randomuser.me/api/portraits/women/21.jpg"
}

###
PATCH  http://localhost:3001/api/users/62665f5510330fac1ebfce25
Content-Type: application/json
{
    "password": "Ukraine"
   
}

###
POST  http://localhost:3001/api/users/login
Content-Type: application/json
{

    "email": "shiv@gmail.com",
    "password": "cof"
   
}

###
POST  http://localhost:3001/api/users/seed