http://localhost:3000

###
GET http://localhost:3000/api/users/
Authorization: bearer eyJfaWQiOiI2MjU3OTM3ZWZmNDI5NzBlZmIyMDJhZTEiLCJmaXJzdG5hbWUiOiJTaGl2aSIsImxhc3RuYW1lIjoiaGV5IiwiaGFuZGxlIjoic2hpdiIsImVtYWlsIjoic2hpdkBnbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yMS5qcGciLCJpZCI6NiwiaWF0IjoxNjQ5OTUzNzA2fQ.Bii179_xMxjN_fLCRTk97FoMwQ0-5Yuq41QhioS7hxY

###
GET http://localhost:3000/api/users/handle/shivi

###
GET http://localhost:3000/api/users/62579361ff42970efb202add

###
DELETE  http://localhost:3000/api/users/62579361ff42970efb202add


###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "firstname": "Shivi",
    "lastname": "hey",
    "handle": "shiv",
    "password": "cof",
    "email": "shiv@gmail.com",
    "pic": "https://randomuser.me/api/portraits/women/21.jpg"
}

###
PATCH  http://localhost:3000/api/users/2
Content-Type: application/json

{

    "lastname": "Putin III",
    "password": "Ukraine",
    "email": "save@ukraine.com"
   
}

###
POST  http://localhost:3000/api/users/login
Content-Type: application/json

{

    "email": "shiv@gmail.com",
    "password": "cof"
   
}

###
POST  http://localhost:3000/api/users/seed
