###
GET http://localhost:3001/api/tasks/

###
GET http://localhost:3001/api/tasks/todo/626b9cd7f1049eff75f08ece
//Authorization: bearer eyJfaWQiOiI2MjU3OTM3ZWZmNDI5NzBlZmIyMDJhZTEiLCJmaXJzdG5hbWUiOiJTaGl2aSIsImxhc3RuYW1lIjoiaGV5IiwiaGFuZGxlIjoic2hpdiIsImVtYWlsIjoic2hpdkBnbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yMS5qcGciLCJpZCI6NiwiaWF0IjoxNjQ5OTUzNzA2fQ.Bii179_xMxjN_fLCRTk97FoMwQ0-5Yuq41QhioS7hxY

###
GET http://localhost:3001/api/tasks/shivi
//Authorization: bearer eyJfaWQiOiI2MjU3OTM3ZWZmNDI5NzBlZmIyMDJhZTEiLCJmaXJzdG5hbWUiOiJTaGl2aSIsImxhc3RuYW1lIjoiaGV5IiwiaGFuZGxlIjoic2hpdiIsImVtYWlsIjoic2hpdkBnbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yMS5qcGciLCJpZCI6NiwiaWF0IjoxNjQ5OTUzNzA2fQ.Bii179_xMxjN_fLCRTk97FoMwQ0-5Yuq41QhioS7hxY

###
DELETE  http://localhost:3001/api/tasks/626b9cd7f1049eff75f08ece
Authorization: bearer eyJfaWQiOiI2MjU3OTM3ZWZmNDI5NzBlZmIyMDJhZTEiLCJmaXJzdG5hbWUiOiJTaGl2aSIsImxhc3RuYW1lIjoiaGV5IiwiaGFuZGxlIjoic2hpdiIsImVtYWlsIjoic2hpdkBnbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yMS5qcGciLCJpZCI6NiwiaWF0IjoxNjQ5OTUzNzA2fQ.Bii179_xMxjN_fLCRTk97FoMwQ0-5Yuq41QhioS7hxY


###
POST http://localhost:3001/api/tasks
Content-Type: application/json
//Authorization: bearer eyJfaWQiOiI2MjU3OTM3ZWZmNDI5NzBlZmIyMDJhZTEiLCJmaXJzdG5hbWUiOiJTaGl2aSIsImxhc3RuYW1lIjoiaGV5IiwiaGFuZGxlIjoic2hpdiIsImVtYWlsIjoic2hpdkBnbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yMS5qcGciLCJpZCI6NiwiaWF0IjoxNjQ5OTUzNzA2fQ.Bii179_xMxjN_fLCRTk97FoMwQ0-5Yuq41QhioS7hxY


    {
        "title": "Connect DB", 
        "isDone": false, 
        "author": "joebiden", 
        "assignedTo": "juli"
    }

###
PATCH  http://localhost:3001/api/tasks/626b9cd7f1049eff75f08ecf
Content-Type: application/json
//Authorization: bearer eyJfaWQiOiI2MjU3OTM3ZWZmNDI5NzBlZmIyMDJhZTEiLCJmaXJzdG5hbWUiOiJTaGl2aSIsImxhc3RuYW1lIjoiaGV5IiwiaGFuZGxlIjoic2hpdiIsImVtYWlsIjoic2hpdkBnbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yMS5qcGciLCJpZCI6NiwiaWF0IjoxNjQ5OTUzNzA2fQ.Bii179_xMxjN_fLCRTk97FoMwQ0-5Yuq41QhioS7hxY


{
    "author": "joebiden"
}

###
POST http://localhost:3001/api/tasks/seed
//Authorization: bearer eyJfaWQiOiI2MjU3OTM3ZWZmNDI5NzBlZmIyMDJhZTEiLCJmaXJzdG5hbWUiOiJTaGl2aSIsImxhc3RuYW1lIjoiaGV5IiwiaGFuZGxlIjoic2hpdiIsImVtYWlsIjoic2hpdkBnbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yMS5qcGciLCJpZCI6NiwiaWF0IjoxNjQ5OTUzNzA2fQ.Bii179_xMxjN_fLCRTk97FoMwQ0-5Yuq41QhioS7hxY
